//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/inputs/Inputs_Party.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace Fulbo.Input
{
    public partial class @FulboInputs: IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @FulboInputs()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""Inputs_Party"",
    ""maps"": [
        {
            ""name"": ""Player1"",
            ""id"": ""196c906f-5f3d-4ea6-8314-251b30ae5a16"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""178c66ec-cee9-4616-8059-20383af3d63d"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Kick"",
                    ""type"": ""Button"",
                    ""id"": ""84b91808-5837-463a-b0d2-f0a76920e6cc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pass"",
                    ""type"": ""Button"",
                    ""id"": ""a3f3267e-3166-413e-8718-c4a81ff1c1b7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Run"",
                    ""type"": ""Button"",
                    ""id"": ""90f55c13-204b-4c92-8dba-4105b9df7d7a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Enter"",
                    ""type"": ""Button"",
                    ""id"": ""2ad5f698-d814-42e5-b4da-1c040d6360aa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Powerup"",
                    ""type"": ""Button"",
                    ""id"": ""acb99088-e0d3-4fe8-9b76-3b138160fc53"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""c841076d-0545-4d19-87fa-45c16333beff"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Up"",
                    ""id"": ""c145b9f4-f37a-4bdc-ae64-517bb672329a"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Down"",
                    ""id"": ""b99bcc29-26a6-4225-8fe6-f99241171855"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Left"",
                    ""id"": ""89f5df8c-c211-4b87-807c-6810667fe0f4"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Right"",
                    ""id"": ""6bf19f7b-ec73-4e9d-8ff2-901149b24b45"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""9aaa9796-5e1b-406a-bbe6-b51f561b0225"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Kick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""acbe3b7d-525e-490c-8487-e0f4060eef79"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Pass"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""21419fd2-0280-4bb8-a784-462c73ba4f0c"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c25bb8e0-19a7-4cbd-8b47-d427f6c76949"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Enter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""805d9b4f-50bf-4feb-88d1-cb29acc5af7b"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Powerup"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Player2"",
            ""id"": ""74e10de6-ce59-4c8d-8af7-c30a6291e4cd"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""8f2aff46-06d0-407c-86b4-2d38f888d109"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Kick"",
                    ""type"": ""Button"",
                    ""id"": ""86b6d5ad-b94f-4730-9f05-6f52559ab37f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pass"",
                    ""type"": ""Button"",
                    ""id"": ""8fbff09d-758c-463e-a80c-9c810d10d505"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Run"",
                    ""type"": ""Button"",
                    ""id"": ""6c37f9be-4c98-4eee-971b-09064aba0f12"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Powerup"",
                    ""type"": ""Button"",
                    ""id"": ""b273ca77-53f6-4591-b64b-fbbb1164b11a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""057ee4ca-3e86-4eb3-8169-b66fd6d793dd"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Up"",
                    ""id"": ""25c25963-294e-411b-97f7-8f8b30d40831"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Down"",
                    ""id"": ""e4c20da5-cd26-443b-b8e9-ef0f2bf7ccd9"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Left"",
                    ""id"": ""512a13c9-5834-4308-846a-381bba77d23e"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Right"",
                    ""id"": ""188352bc-e940-4c47-8659-609bb168ca6c"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""9bcd0496-ab83-4405-9d46-2f76961be2f0"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Kick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6ecf4f2d-205f-45e3-9bb0-094d7ffa1053"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Pass"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ac3078d6-6521-4c7c-b587-abfde06ab7f2"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ccce35c9-4dc9-47b8-b084-3b4a27ba66cb"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Powerup"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Player3"",
            ""id"": ""22ef22c6-ff8e-4bcc-9007-302ef8f89e80"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""3d396a93-507d-4506-a211-95b70b4b9703"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Kick"",
                    ""type"": ""Button"",
                    ""id"": ""37eebe9b-7308-4aa3-bcd8-51b32e6b0462"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pass"",
                    ""type"": ""Button"",
                    ""id"": ""bce9fa15-e6c6-4856-b8df-40143d246aa2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Run"",
                    ""type"": ""Button"",
                    ""id"": ""1b85f1d8-b4ad-4e44-953d-ebefa51730c4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Powerup"",
                    ""type"": ""Button"",
                    ""id"": ""5936b401-fbfb-4290-983c-664c20a9fb16"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""3f21690f-e195-458a-a59f-a2c9898b951c"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Up"",
                    ""id"": ""dba5c364-7a6a-47a8-ac37-1613f1412b8b"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Down"",
                    ""id"": ""910dbb9d-949d-4a77-ad7e-fb346cc92a89"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Left"",
                    ""id"": ""38c3a0bc-0dd9-4f9a-8833-99df524061d3"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Right"",
                    ""id"": ""6207fcc6-0adf-451d-993e-b6aac9cfc4a2"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""7f5bbbec-dd60-4e69-a5ad-b8dbb10c498f"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Kick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""24027e98-69d1-45a5-bcef-72f09d3b9868"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Pass"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""15dc76da-bc4a-41d4-82a9-870508f32a02"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0b961481-a905-472b-a6e3-361144be69fc"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Powerup"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Player4"",
            ""id"": ""cfc6420b-bb87-4b43-882a-74317e2c432f"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""4f06d631-eb74-456b-983a-8d7e35f33073"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Kick"",
                    ""type"": ""Button"",
                    ""id"": ""f0f2a9f1-2790-4c4b-bb6b-4791cef7d2eb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pass"",
                    ""type"": ""Button"",
                    ""id"": ""09bc03e9-39ba-4145-b26f-830347ccf7ba"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Run"",
                    ""type"": ""Button"",
                    ""id"": ""a93394e8-4f3d-4769-a4e8-f176e1875407"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Powerup"",
                    ""type"": ""Button"",
                    ""id"": ""e9825ad4-b846-45d8-a3d6-a339a3245d2b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""226db7fe-2e5e-458e-b899-7dff35b3df8d"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Up"",
                    ""id"": ""487aeb99-18aa-439a-a417-2479c5da068b"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Down"",
                    ""id"": ""da540aa9-352f-4e1c-a06d-77cfa0e7ba53"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Left"",
                    ""id"": ""f8c084e3-05c5-444d-bfce-a48f04cc1dba"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Right"",
                    ""id"": ""45ee977a-0f92-4fda-9000-92974b1c75b9"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""38676382-dcf6-4d58-b3c2-eb837eb25c22"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Kick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7cb77379-fdf6-4622-bb49-b412118b2912"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Pass"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c7aadfcd-9536-4444-9488-1aabb15d6cf6"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ea23c584-4b11-4f0d-b877-54872c260f64"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Powerup"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI"",
            ""id"": ""c8cb1f1c-47e5-4cc2-a1a1-7d397f9829f1"",
            ""actions"": [
                {
                    ""name"": ""VolUp"",
                    ""type"": ""Button"",
                    ""id"": ""b2bcec64-464a-44fc-8117-de71afe4cc7f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""VolDown"",
                    ""type"": ""Button"",
                    ""id"": ""ade8a6be-66eb-42f2-99fc-acc01b6dfe09"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""034bbf08-3722-4447-b9b1-05bee0f77259"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard;UI"",
                    ""action"": ""VolUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8402caec-7451-4fa5-a621-c5b0431cbde9"",
                    ""path"": ""<Keyboard>/n"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard;UI"",
                    ""action"": ""VolDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard"",
            ""bindingGroup"": ""Keyboard"",
            ""devices"": []
        },
        {
            ""name"": ""UI"",
            ""bindingGroup"": ""UI"",
            ""devices"": []
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": []
        }
    ]
}");
            // Player1
            m_Player1 = asset.FindActionMap("Player1", throwIfNotFound: true);
            m_Player1_Move = m_Player1.FindAction("Move", throwIfNotFound: true);
            m_Player1_Kick = m_Player1.FindAction("Kick", throwIfNotFound: true);
            m_Player1_Pass = m_Player1.FindAction("Pass", throwIfNotFound: true);
            m_Player1_Run = m_Player1.FindAction("Run", throwIfNotFound: true);
            m_Player1_Enter = m_Player1.FindAction("Enter", throwIfNotFound: true);
            m_Player1_Powerup = m_Player1.FindAction("Powerup", throwIfNotFound: true);
            // Player2
            m_Player2 = asset.FindActionMap("Player2", throwIfNotFound: true);
            m_Player2_Move = m_Player2.FindAction("Move", throwIfNotFound: true);
            m_Player2_Kick = m_Player2.FindAction("Kick", throwIfNotFound: true);
            m_Player2_Pass = m_Player2.FindAction("Pass", throwIfNotFound: true);
            m_Player2_Run = m_Player2.FindAction("Run", throwIfNotFound: true);
            m_Player2_Powerup = m_Player2.FindAction("Powerup", throwIfNotFound: true);
            // Player3
            m_Player3 = asset.FindActionMap("Player3", throwIfNotFound: true);
            m_Player3_Move = m_Player3.FindAction("Move", throwIfNotFound: true);
            m_Player3_Kick = m_Player3.FindAction("Kick", throwIfNotFound: true);
            m_Player3_Pass = m_Player3.FindAction("Pass", throwIfNotFound: true);
            m_Player3_Run = m_Player3.FindAction("Run", throwIfNotFound: true);
            m_Player3_Powerup = m_Player3.FindAction("Powerup", throwIfNotFound: true);
            // Player4
            m_Player4 = asset.FindActionMap("Player4", throwIfNotFound: true);
            m_Player4_Move = m_Player4.FindAction("Move", throwIfNotFound: true);
            m_Player4_Kick = m_Player4.FindAction("Kick", throwIfNotFound: true);
            m_Player4_Pass = m_Player4.FindAction("Pass", throwIfNotFound: true);
            m_Player4_Run = m_Player4.FindAction("Run", throwIfNotFound: true);
            m_Player4_Powerup = m_Player4.FindAction("Powerup", throwIfNotFound: true);
            // UI
            m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
            m_UI_VolUp = m_UI.FindAction("VolUp", throwIfNotFound: true);
            m_UI_VolDown = m_UI.FindAction("VolDown", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }

        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Player1
        private readonly InputActionMap m_Player1;
        private List<IPlayer1Actions> m_Player1ActionsCallbackInterfaces = new List<IPlayer1Actions>();
        private readonly InputAction m_Player1_Move;
        private readonly InputAction m_Player1_Kick;
        private readonly InputAction m_Player1_Pass;
        private readonly InputAction m_Player1_Run;
        private readonly InputAction m_Player1_Enter;
        private readonly InputAction m_Player1_Powerup;
        public struct Player1Actions
        {
            private @FulboInputs m_Wrapper;
            public Player1Actions(@FulboInputs wrapper) { m_Wrapper = wrapper; }
            public InputAction @Move => m_Wrapper.m_Player1_Move;
            public InputAction @Kick => m_Wrapper.m_Player1_Kick;
            public InputAction @Pass => m_Wrapper.m_Player1_Pass;
            public InputAction @Run => m_Wrapper.m_Player1_Run;
            public InputAction @Enter => m_Wrapper.m_Player1_Enter;
            public InputAction @Powerup => m_Wrapper.m_Player1_Powerup;
            public InputActionMap Get() { return m_Wrapper.m_Player1; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(Player1Actions set) { return set.Get(); }
            public void AddCallbacks(IPlayer1Actions instance)
            {
                if (instance == null || m_Wrapper.m_Player1ActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_Player1ActionsCallbackInterfaces.Add(instance);
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Kick.started += instance.OnKick;
                @Kick.performed += instance.OnKick;
                @Kick.canceled += instance.OnKick;
                @Pass.started += instance.OnPass;
                @Pass.performed += instance.OnPass;
                @Pass.canceled += instance.OnPass;
                @Run.started += instance.OnRun;
                @Run.performed += instance.OnRun;
                @Run.canceled += instance.OnRun;
                @Enter.started += instance.OnEnter;
                @Enter.performed += instance.OnEnter;
                @Enter.canceled += instance.OnEnter;
                @Powerup.started += instance.OnPowerup;
                @Powerup.performed += instance.OnPowerup;
                @Powerup.canceled += instance.OnPowerup;
            }

            private void UnregisterCallbacks(IPlayer1Actions instance)
            {
                @Move.started -= instance.OnMove;
                @Move.performed -= instance.OnMove;
                @Move.canceled -= instance.OnMove;
                @Kick.started -= instance.OnKick;
                @Kick.performed -= instance.OnKick;
                @Kick.canceled -= instance.OnKick;
                @Pass.started -= instance.OnPass;
                @Pass.performed -= instance.OnPass;
                @Pass.canceled -= instance.OnPass;
                @Run.started -= instance.OnRun;
                @Run.performed -= instance.OnRun;
                @Run.canceled -= instance.OnRun;
                @Enter.started -= instance.OnEnter;
                @Enter.performed -= instance.OnEnter;
                @Enter.canceled -= instance.OnEnter;
                @Powerup.started -= instance.OnPowerup;
                @Powerup.performed -= instance.OnPowerup;
                @Powerup.canceled -= instance.OnPowerup;
            }

            public void RemoveCallbacks(IPlayer1Actions instance)
            {
                if (m_Wrapper.m_Player1ActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IPlayer1Actions instance)
            {
                foreach (var item in m_Wrapper.m_Player1ActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_Player1ActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public Player1Actions @Player1 => new Player1Actions(this);

        // Player2
        private readonly InputActionMap m_Player2;
        private List<IPlayer2Actions> m_Player2ActionsCallbackInterfaces = new List<IPlayer2Actions>();
        private readonly InputAction m_Player2_Move;
        private readonly InputAction m_Player2_Kick;
        private readonly InputAction m_Player2_Pass;
        private readonly InputAction m_Player2_Run;
        private readonly InputAction m_Player2_Powerup;
        public struct Player2Actions
        {
            private @FulboInputs m_Wrapper;
            public Player2Actions(@FulboInputs wrapper) { m_Wrapper = wrapper; }
            public InputAction @Move => m_Wrapper.m_Player2_Move;
            public InputAction @Kick => m_Wrapper.m_Player2_Kick;
            public InputAction @Pass => m_Wrapper.m_Player2_Pass;
            public InputAction @Run => m_Wrapper.m_Player2_Run;
            public InputAction @Powerup => m_Wrapper.m_Player2_Powerup;
            public InputActionMap Get() { return m_Wrapper.m_Player2; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(Player2Actions set) { return set.Get(); }
            public void AddCallbacks(IPlayer2Actions instance)
            {
                if (instance == null || m_Wrapper.m_Player2ActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_Player2ActionsCallbackInterfaces.Add(instance);
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Kick.started += instance.OnKick;
                @Kick.performed += instance.OnKick;
                @Kick.canceled += instance.OnKick;
                @Pass.started += instance.OnPass;
                @Pass.performed += instance.OnPass;
                @Pass.canceled += instance.OnPass;
                @Run.started += instance.OnRun;
                @Run.performed += instance.OnRun;
                @Run.canceled += instance.OnRun;
                @Powerup.started += instance.OnPowerup;
                @Powerup.performed += instance.OnPowerup;
                @Powerup.canceled += instance.OnPowerup;
            }

            private void UnregisterCallbacks(IPlayer2Actions instance)
            {
                @Move.started -= instance.OnMove;
                @Move.performed -= instance.OnMove;
                @Move.canceled -= instance.OnMove;
                @Kick.started -= instance.OnKick;
                @Kick.performed -= instance.OnKick;
                @Kick.canceled -= instance.OnKick;
                @Pass.started -= instance.OnPass;
                @Pass.performed -= instance.OnPass;
                @Pass.canceled -= instance.OnPass;
                @Run.started -= instance.OnRun;
                @Run.performed -= instance.OnRun;
                @Run.canceled -= instance.OnRun;
                @Powerup.started -= instance.OnPowerup;
                @Powerup.performed -= instance.OnPowerup;
                @Powerup.canceled -= instance.OnPowerup;
            }

            public void RemoveCallbacks(IPlayer2Actions instance)
            {
                if (m_Wrapper.m_Player2ActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IPlayer2Actions instance)
            {
                foreach (var item in m_Wrapper.m_Player2ActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_Player2ActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public Player2Actions @Player2 => new Player2Actions(this);

        // Player3
        private readonly InputActionMap m_Player3;
        private List<IPlayer3Actions> m_Player3ActionsCallbackInterfaces = new List<IPlayer3Actions>();
        private readonly InputAction m_Player3_Move;
        private readonly InputAction m_Player3_Kick;
        private readonly InputAction m_Player3_Pass;
        private readonly InputAction m_Player3_Run;
        private readonly InputAction m_Player3_Powerup;
        public struct Player3Actions
        {
            private @FulboInputs m_Wrapper;
            public Player3Actions(@FulboInputs wrapper) { m_Wrapper = wrapper; }
            public InputAction @Move => m_Wrapper.m_Player3_Move;
            public InputAction @Kick => m_Wrapper.m_Player3_Kick;
            public InputAction @Pass => m_Wrapper.m_Player3_Pass;
            public InputAction @Run => m_Wrapper.m_Player3_Run;
            public InputAction @Powerup => m_Wrapper.m_Player3_Powerup;
            public InputActionMap Get() { return m_Wrapper.m_Player3; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(Player3Actions set) { return set.Get(); }
            public void AddCallbacks(IPlayer3Actions instance)
            {
                if (instance == null || m_Wrapper.m_Player3ActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_Player3ActionsCallbackInterfaces.Add(instance);
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Kick.started += instance.OnKick;
                @Kick.performed += instance.OnKick;
                @Kick.canceled += instance.OnKick;
                @Pass.started += instance.OnPass;
                @Pass.performed += instance.OnPass;
                @Pass.canceled += instance.OnPass;
                @Run.started += instance.OnRun;
                @Run.performed += instance.OnRun;
                @Run.canceled += instance.OnRun;
                @Powerup.started += instance.OnPowerup;
                @Powerup.performed += instance.OnPowerup;
                @Powerup.canceled += instance.OnPowerup;
            }

            private void UnregisterCallbacks(IPlayer3Actions instance)
            {
                @Move.started -= instance.OnMove;
                @Move.performed -= instance.OnMove;
                @Move.canceled -= instance.OnMove;
                @Kick.started -= instance.OnKick;
                @Kick.performed -= instance.OnKick;
                @Kick.canceled -= instance.OnKick;
                @Pass.started -= instance.OnPass;
                @Pass.performed -= instance.OnPass;
                @Pass.canceled -= instance.OnPass;
                @Run.started -= instance.OnRun;
                @Run.performed -= instance.OnRun;
                @Run.canceled -= instance.OnRun;
                @Powerup.started -= instance.OnPowerup;
                @Powerup.performed -= instance.OnPowerup;
                @Powerup.canceled -= instance.OnPowerup;
            }

            public void RemoveCallbacks(IPlayer3Actions instance)
            {
                if (m_Wrapper.m_Player3ActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IPlayer3Actions instance)
            {
                foreach (var item in m_Wrapper.m_Player3ActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_Player3ActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public Player3Actions @Player3 => new Player3Actions(this);

        // Player4
        private readonly InputActionMap m_Player4;
        private List<IPlayer4Actions> m_Player4ActionsCallbackInterfaces = new List<IPlayer4Actions>();
        private readonly InputAction m_Player4_Move;
        private readonly InputAction m_Player4_Kick;
        private readonly InputAction m_Player4_Pass;
        private readonly InputAction m_Player4_Run;
        private readonly InputAction m_Player4_Powerup;
        public struct Player4Actions
        {
            private @FulboInputs m_Wrapper;
            public Player4Actions(@FulboInputs wrapper) { m_Wrapper = wrapper; }
            public InputAction @Move => m_Wrapper.m_Player4_Move;
            public InputAction @Kick => m_Wrapper.m_Player4_Kick;
            public InputAction @Pass => m_Wrapper.m_Player4_Pass;
            public InputAction @Run => m_Wrapper.m_Player4_Run;
            public InputAction @Powerup => m_Wrapper.m_Player4_Powerup;
            public InputActionMap Get() { return m_Wrapper.m_Player4; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(Player4Actions set) { return set.Get(); }
            public void AddCallbacks(IPlayer4Actions instance)
            {
                if (instance == null || m_Wrapper.m_Player4ActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_Player4ActionsCallbackInterfaces.Add(instance);
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Kick.started += instance.OnKick;
                @Kick.performed += instance.OnKick;
                @Kick.canceled += instance.OnKick;
                @Pass.started += instance.OnPass;
                @Pass.performed += instance.OnPass;
                @Pass.canceled += instance.OnPass;
                @Run.started += instance.OnRun;
                @Run.performed += instance.OnRun;
                @Run.canceled += instance.OnRun;
                @Powerup.started += instance.OnPowerup;
                @Powerup.performed += instance.OnPowerup;
                @Powerup.canceled += instance.OnPowerup;
            }

            private void UnregisterCallbacks(IPlayer4Actions instance)
            {
                @Move.started -= instance.OnMove;
                @Move.performed -= instance.OnMove;
                @Move.canceled -= instance.OnMove;
                @Kick.started -= instance.OnKick;
                @Kick.performed -= instance.OnKick;
                @Kick.canceled -= instance.OnKick;
                @Pass.started -= instance.OnPass;
                @Pass.performed -= instance.OnPass;
                @Pass.canceled -= instance.OnPass;
                @Run.started -= instance.OnRun;
                @Run.performed -= instance.OnRun;
                @Run.canceled -= instance.OnRun;
                @Powerup.started -= instance.OnPowerup;
                @Powerup.performed -= instance.OnPowerup;
                @Powerup.canceled -= instance.OnPowerup;
            }

            public void RemoveCallbacks(IPlayer4Actions instance)
            {
                if (m_Wrapper.m_Player4ActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IPlayer4Actions instance)
            {
                foreach (var item in m_Wrapper.m_Player4ActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_Player4ActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public Player4Actions @Player4 => new Player4Actions(this);

        // UI
        private readonly InputActionMap m_UI;
        private List<IUIActions> m_UIActionsCallbackInterfaces = new List<IUIActions>();
        private readonly InputAction m_UI_VolUp;
        private readonly InputAction m_UI_VolDown;
        public struct UIActions
        {
            private @FulboInputs m_Wrapper;
            public UIActions(@FulboInputs wrapper) { m_Wrapper = wrapper; }
            public InputAction @VolUp => m_Wrapper.m_UI_VolUp;
            public InputAction @VolDown => m_Wrapper.m_UI_VolDown;
            public InputActionMap Get() { return m_Wrapper.m_UI; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
            public void AddCallbacks(IUIActions instance)
            {
                if (instance == null || m_Wrapper.m_UIActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_UIActionsCallbackInterfaces.Add(instance);
                @VolUp.started += instance.OnVolUp;
                @VolUp.performed += instance.OnVolUp;
                @VolUp.canceled += instance.OnVolUp;
                @VolDown.started += instance.OnVolDown;
                @VolDown.performed += instance.OnVolDown;
                @VolDown.canceled += instance.OnVolDown;
            }

            private void UnregisterCallbacks(IUIActions instance)
            {
                @VolUp.started -= instance.OnVolUp;
                @VolUp.performed -= instance.OnVolUp;
                @VolUp.canceled -= instance.OnVolUp;
                @VolDown.started -= instance.OnVolDown;
                @VolDown.performed -= instance.OnVolDown;
                @VolDown.canceled -= instance.OnVolDown;
            }

            public void RemoveCallbacks(IUIActions instance)
            {
                if (m_Wrapper.m_UIActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IUIActions instance)
            {
                foreach (var item in m_Wrapper.m_UIActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_UIActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public UIActions @UI => new UIActions(this);
        private int m_KeyboardSchemeIndex = -1;
        public InputControlScheme KeyboardScheme
        {
            get
            {
                if (m_KeyboardSchemeIndex == -1) m_KeyboardSchemeIndex = asset.FindControlSchemeIndex("Keyboard");
                return asset.controlSchemes[m_KeyboardSchemeIndex];
            }
        }
        private int m_UISchemeIndex = -1;
        public InputControlScheme UIScheme
        {
            get
            {
                if (m_UISchemeIndex == -1) m_UISchemeIndex = asset.FindControlSchemeIndex("UI");
                return asset.controlSchemes[m_UISchemeIndex];
            }
        }
        private int m_GamepadSchemeIndex = -1;
        public InputControlScheme GamepadScheme
        {
            get
            {
                if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
                return asset.controlSchemes[m_GamepadSchemeIndex];
            }
        }
        public interface IPlayer1Actions
        {
            void OnMove(InputAction.CallbackContext context);
            void OnKick(InputAction.CallbackContext context);
            void OnPass(InputAction.CallbackContext context);
            void OnRun(InputAction.CallbackContext context);
            void OnEnter(InputAction.CallbackContext context);
            void OnPowerup(InputAction.CallbackContext context);
        }
        public interface IPlayer2Actions
        {
            void OnMove(InputAction.CallbackContext context);
            void OnKick(InputAction.CallbackContext context);
            void OnPass(InputAction.CallbackContext context);
            void OnRun(InputAction.CallbackContext context);
            void OnPowerup(InputAction.CallbackContext context);
        }
        public interface IPlayer3Actions
        {
            void OnMove(InputAction.CallbackContext context);
            void OnKick(InputAction.CallbackContext context);
            void OnPass(InputAction.CallbackContext context);
            void OnRun(InputAction.CallbackContext context);
            void OnPowerup(InputAction.CallbackContext context);
        }
        public interface IPlayer4Actions
        {
            void OnMove(InputAction.CallbackContext context);
            void OnKick(InputAction.CallbackContext context);
            void OnPass(InputAction.CallbackContext context);
            void OnRun(InputAction.CallbackContext context);
            void OnPowerup(InputAction.CallbackContext context);
        }
        public interface IUIActions
        {
            void OnVolUp(InputAction.CallbackContext context);
            void OnVolDown(InputAction.CallbackContext context);
        }
    }
}
